import businessPlanet from "./../img/businessPlanet.png";
import healthplanetbg from "./../img/healthplanetbg.jpeg";
import JusticePlanet from "./../img/JusticePlanet.png";
import techplanetbg from "./../img/techplanetbg.jpeg";

export const workhabit = [{
        quiz: "Working Safety",
    },
    {
        quiz: "Teamwork",
    },
    {
        quiz: "Reliability",
    },
    {
        quiz: "Teamwork",
    },
    {
        quiz: "Organizations",
    },
    {
        quiz: "Working independently",
    },
    {
        quiz: "Initiative",
    },
    {
        quiz: "Self-advocacy",
    },
    {
        quiz: "Customer Service",
    },
    {
        quiz: "Enterpreneurship",
    },
    {
        quiz: "Leadership Skills",
    },
];

export const essentials = [{
        quiz: "Reading"
    },
    {
        quiz: "Writing"
    },
    {
        quiz: "Document Use"
    },
    {
        quiz: "Digital Technology"
    },
    {
        quiz: "Oral Communication"
    },
    {
        quiz: "Money Math"
    },
    {
        quiz: "Scheduling or Budgeting and Accounting"
    },
    {
        quiz: "Measurement and calculation"
    },
    {
        quiz: "Data analysis"
    },
    {
        quiz: "Numerical estimation"
    },
    {
        quiz: "Job Task Planning and Organization"
    },
    {
        quiz: "Decision Making"
    },
    {
        quiz: "Problem Solving"
    },
    {
        quiz: "Finding Information"
    },
    {
        quiz: "Critical Thinking"
    },
];

export const jobs = [{
        planetId: 0,
        planetName: "Business Planet",
        planetStreets: [{
                streetId: 0,
                streetName: "Corporate Road",
                jobs: [{
                        jobid: 0,
                        jobname: "Sales coordinator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "project coordinator",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "accountant",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "HR specialist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Sales Representative",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Marketing Manager",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
            {
                streetId: 1,
                streetName: "Banking Avenue",
                jobs: [{
                        jobid: 0,
                        jobname: "Sales coordinator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "project coordinator",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "accountant",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "HR specialist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Sales Representative",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Marketing Manager",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
            {
                streetId: 2,
                streetName: "wall street",
                jobs: [{
                        jobid: 0,
                        jobname: "Sales coordinator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "project coordinator",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "accountant",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "HR specialist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Sales Representative",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Marketing Manager",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
            {
                streetId: 3,
                streetName: "grocers lane",
                jobs: [{
                        jobid: 0,
                        jobname: "Sales coordinator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "project coordinator",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "accountant",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "HR specialist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Sales Representative",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Marketing Manager",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
        ],
        bgImg: businessPlanet,
    },
    {
        planetId: 1,
        planetName: "Artsy Planet",
        planetStreets: [{
                streetId: 0,
                streetName: "Graphic avenue",
                jobs: [{
                        jobid: 0,
                        jobname: "Graphic Designer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Fine Artist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Animator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "Art Director",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Art Teacher",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Curator",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 6,
                        jobname: "Art Critic",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 7,
                        jobname: "Art Therapist",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
            {
                streetId: 1,
                streetName: "Art Therapist",
                jobs: [{
                        jobid: 0,
                        jobname: "Graphic Designer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Fine Artist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Animator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "Art Director",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Art Teacher",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Curator",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 6,
                        jobname: "Art Critic",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 7,
                        jobname: "Art Therapist",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
            {
                streetId: 2,
                streetName: "theater dr",
                jobs: [{
                        jobid: 0,
                        jobname: "Graphic Designer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Fine Artist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Animator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "Art Director",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Art Teacher",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Curator",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 6,
                        jobname: "Art Critic",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 7,
                        jobname: "Art Therapist",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
            {
                streetId: 3,
                streetName: "music box",
                jobs: [{
                        jobid: 0,
                        jobname: "Graphic Designer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Fine Artist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Animator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 3,
                        jobname: "Art Director",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Art Teacher",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 5,
                        jobname: "Curator",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 6,
                        jobname: "Art Critic",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 7,
                        jobname: "Art Therapist",
                        applied: "false",
                        levelofPrep: 2,
                    },
                ],
            },
        ],
        bgImg: techplanetbg,
    },
    {
        planetId: 2,
        planetName: "Home planet self assesment",
        planetStreets: [{
                streetId: 0,
                streetName: "Corporate Road",
                jobs: [{
                        jobid: 1,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 2,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 3,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 4,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 5,
                        jobname: "Software developer",
                        status: "active",
                    },
                ],
            },
            {
                streetId: 1,
                streetName: "Banking Avenue",
                jobs: [{
                        jobid: 1,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 2,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 3,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 4,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 5,
                        jobname: "Software developer",
                        status: "active",
                    },
                ],
            },
            {
                streetId: 2,
                streetName: "wall street",
                jobs: [{
                        jobid: 1,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 2,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 3,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 4,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 5,
                        jobname: "Software developer",
                        status: "active",
                    },
                ],
            },
            {
                streetId: 3,
                streetName: "grocers lane",
                jobs: [{
                        jobid: 1,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 2,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 3,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 4,
                        jobname: "Software developer",
                        status: "active",
                    },
                    {
                        jobid: 5,
                        jobname: "Software developer",
                        status: "active",
                    },
                ],
            },
        ],
        bgImg: businessPlanet,
    },
    {
        planetId: 3,
        planetName: "Health Planet",
        planetStreets: [{
                streetId: 0,
                streetName: "hospital dr",
                jobs: [{
                        jobid: 0,
                        jobname: "Physician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Registered Nurse",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Medical Assistant",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 3,
                        jobname: "Radiologic Technologist",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Physical Therapist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 5,
                        jobname: "Respiratory Therapist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 6,
                        jobname: "Medical Laboratory Technician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                ],
            },
            {
                streetId: 1,
                streetName: "wellness avenue",
                jobs: [{
                        jobid: 0,
                        jobname: "Physician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Registered Nurse",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Medical Assistant",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 3,
                        jobname: "Radiologic Technologist",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Physical Therapist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 5,
                        jobname: "Respiratory Therapist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 6,
                        jobname: "Medical Laboratory Technician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                ],
            },
            {
                streetId: 2,
                streetName: "Care square",
                jobs: [{
                        jobid: 0,
                        jobname: "Physician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Registered Nurse",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Medical Assistant",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 3,
                        jobname: "Radiologic Technologist",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Physical Therapist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 5,
                        jobname: "Respiratory Therapist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 6,
                        jobname: "Medical Laboratory Technician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                ],
            },
            {
                streetId: 3,
                streetName: "Meditation gardens",
                jobs: [{
                        jobid: 0,
                        jobname: "Physician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Registered Nurse",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Medical Assistant",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 3,
                        jobname: "Radiologic Technologist",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Physical Therapist",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 5,
                        jobname: "Respiratory Therapist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 6,
                        jobname: "Medical Laboratory Technician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                ],
            },
            {
                streetId: 4,
                streetName: "PostNatal",
                jobs: [{
                        jobid: 0,
                        jobname: "Physician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Registered Nurse",
                        applied: "true",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Medical Assistant",
                        applied: "true",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 3,
                        jobname: "Radiologic Technologist",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Physical Therapist",
                        applied: "true",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 5,
                        jobname: "Respiratory Therapist",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 6,
                        jobname: "Medical Laboratory Technician",
                        applied: "false",
                        levelofPrep: 4,
                    },
                ],
            },
        ],
        bgImg: healthplanetbg,
    },
    {
        planetId: 4,
        planetName: "Jusice Planet",
        planetStreets: [{
                streetId: 0,
                streetName: "Courthouse",
                jobs: [{
                        jobid: 0,
                        jobname: "Lawyer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Paralegal",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 2,
                        jobname: "Legal Assistant",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 3,
                        jobname: "Judge",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Court Reporter",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Police",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 6,
                        jobname: "Legal Secretary",
                        applied: "false",
                        levelofPrep: 3,
                    },
                ],
            },
            {
                streetId: 1,
                streetName: "Police department",
                jobs: [{
                        jobid: 0,
                        jobname: "Lawyer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Paralegal",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 2,
                        jobname: "Legal Assistant",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 3,
                        jobname: "Judge",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Court Reporter",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Bailiff",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 6,
                        jobname: "Legal Secretary",
                        applied: "false",
                        levelofPrep: 3,
                    },
                ],
            },
            {
                streetId: 2,
                streetName: "Legal avenue",
                jobs: [{
                        jobid: 0,
                        jobname: "Lawyer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Paralegal",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 2,
                        jobname: "Legal Assistant",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 3,
                        jobname: "Judge",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Court Reporter",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Bailiff",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 6,
                        jobname: "Legal Secretary",
                        applied: "false",
                        levelofPrep: 3,
                    },
                ],
            },
            {
                streetId: 3,
                streetName: "Meditation gardens",
                jobs: [{
                        jobid: 0,
                        jobname: "Lawyer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Paralegal",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 2,
                        jobname: "Legal Assistant",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 3,
                        jobname: "Judge",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Court Reporter",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Bailiff",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 6,
                        jobname: "Legal Secretary",
                        applied: "false",
                        levelofPrep: 3,
                    },
                ],
            },
            {
                streetId: 4,
                streetName: "PostNatal",
                jobs: [{
                        jobid: 0,
                        jobname: "Lawyer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Paralegal",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 2,
                        jobname: "Legal Assistant",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 3,
                        jobname: "Judge",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 4,
                        jobname: "Court Reporter",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Bailiff",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 6,
                        jobname: "Legal Secretary",
                        applied: "false",
                        levelofPrep: 3,
                    },
                ],
            },
        ],
        bgImg: JusticePlanet,
    },
    {
        planetId: 5,
        planetName: "planet Tech",
        planetStreets: [{
                streetId: 0,
                streetName: "Software avenue",
                jobs: [{
                        jobid: 0,
                        jobname: "Software Engineer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Data Analyst",
                        applied: "true",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Product Manager",
                        applied: "true",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 3,
                        jobname: "Cybersecurity Analyst",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Mobile Application Developer",
                        applied: "true",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Web Developer",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 6,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 7,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 8,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                ],
            },
            {
                streetId: 1,
                streetName: "Trades Market",
                jobs: [{
                        jobid: 0,
                        jobname: "Software Engineer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Data Analyst",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Product Manager",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 3,
                        jobname: "Cybersecurity Analyst",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Mobile Application Developer",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Web Developer",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 6,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 7,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 8,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                ],
            },
            {
                streetId: 2,
                streetName: "Builders Lane",
                jobs: [{
                        jobid: 0,
                        jobname: "Software Engineer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Data Analyst",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Product Manager",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 3,
                        jobname: "Cybersecurity Analyst",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Mobile Application Developer",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Web Developer",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 6,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 7,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                    {
                        jobid: 8,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 1,
                    },
                ],
            },
            {
                streetId: 3,
                streetName: "Earth dr",
                jobs: [{
                        jobid: 0,
                        jobname: "Software Engineer",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 1,
                        jobname: "Data Analyst",
                        applied: "false",
                        levelofPrep: 3,
                    },
                    {
                        jobid: 2,
                        jobname: "Product Manager",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 3,
                        jobname: "Cybersecurity Analyst",
                        applied: "false",
                        levelofPrep: 4,
                    },
                    {
                        jobid: 4,
                        jobname: "Mobile Application Developer",
                        applied: "false",
                        levelofPrep: 2,
                    },
                    {
                        jobid: 5,
                        jobname: "Web Developer",
                        applied: "false",
                        levelofPrep: 5,
                    },
                    {
                        jobid: 6,
                        jobname: "Network Administrator",
                        applied: "false",
                        levelofPrep: 4,
                    },
                ],
            },
        ],
        bgImg: techplanetbg,
    },
];

const jobArray = [{
        job: "Security Officer",
        salary: "$33,147",
        description: "Keeps an eye on the property by walking around it consistently and making sure nothing suspicious is happening.",
        responsibilities: [
            "Inspect and patrol premises regularly",
            "Monitor property entrance",
            "Secure all exits, doors and windows",
            "Monitor surveillance cameras",
            "Report any suspicious behaviors and happenings",
            "Authorize entrance of people and vehicles",
        ],
        personalCharacteristics: [
            "Physical fitness/strength",
            "Alertness/vigilance/mind on the job",
            "Professionalism",
            "Integrity",
        ],
        essentialSkills: [
            "Lifting",
            "Manage Multiple Tasks",
            "Following Complex Instructions",
            "Emotional Control",
            "Patrolling",
            "Attention to Detail",
            "Objectivity",
            "Safety Management",
            "Reporting Skills",
            "Dependability",
        ],
        personalSkills: [],
        educationRequired: "High School Diploma",
        certifications: ["40 hour security guard training"],
        experience: "",
        levelOfPreparation: 1,
        icon: "",
        sources: [""],
    },
    {
        job: "Police",
        salary: "$72,459",
        description: "Patrols their zone and protects anyone that needs it.",
        responsibilities: [
            "Patrol assigned areas to maintain public safety",
            "Investigate crimes and accidents",
            "Arrest criminal suspects",
            "Provide emergency assistance to victims",
            "Supervise and co-ordinate the work",
        ],
        personalCharacteristics: [
            "18 Years and older",
            "Critical Thinking",
            "Reliability",
            "Physically and mentally fit",
            "Good moral character and habits",
        ],
        essentialSkills: [
            "Problem Solving",
            "Oral Communication",
            "Document use",
            "Finding information",
            "Public service attitude",
            "Safety attitude",
        ],
        personalSkills: ["CPR & First Aid Level C"],
        educationRequired: "High School Diploma",
        certifications: ["Driver's License (Class G)"],
        experience: "",
        levelOfPreparation: 3,
        icon: "",
        sources: [
            "https://www.peterboroughpolice.com/en/learn/police-job-postings.aspx#Do-you-have-what-it-takes",
        ],
    },
    {
        job: "Paralegal",
        salary: "$64,269",
        description: "Help lawyers interview witnesses, prepare documents and research for court",
        responsibilities: [
            "Assist lawyers by interviewing clients, witnesses and other related parties",
            "Assembling documentary evidence",
            "Preparing trial briefs",
            "Assist lawyers in preparation for mediation",
            "Research records, court files and other legal documents",
        ],
        personalCharacteristics: [
            "Hardworking",
            "Dedicated",
            "Fairly introverted",
            "Organized",
            "Independent",
            "Genuine desire to help others",
        ],
        essentialSkills: [
            "STRONG READING, WRITING, AND RESEARCH SKILLS",
            "Attention to detail",
            "ORGANIZATION AND TIME MANAGEMENT",
            "Writing ability",
        ],
        personalSkills: [
            "EXCELLENT COMMUNICATION AND INTERPERSONAL SKILLS",
            "Empathy and teamwork",
        ],
        educationRequired: "Ontario Secondary School Diploma (OSSD) or equivalent, which includes a grade 12 English credit",
        certifications: [
            "Bachelors degree in Law",
            "Law College Diploma",
            "In-House training from a law firm",
            "Other legal establishments",
        ],
        experience: "",
        levelOfPreparation: 3,
        icon: "",
        sources: [""],
    },
];